services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nowo\QrCodeBundle\Config\ProfileResolver:
    arguments:
      $profiles: '%nowo_qr_code.profiles%'
      $defaultProfile: '%nowo_qr_code.default_profile%'
      $useDatabaseConfig: '%nowo_qr_code.use_database_config%'
      $profileRepository: null

  Nowo\QrCodeBundle\Service\QrCodeService:
    arguments:
      $profileResolver: '@Nowo\QrCodeBundle\Config\ProfileResolver'

  Nowo\QrCodeBundle\Twig\QrCodeExtension: ~
